export const GAME_CONFIG = {
  SCROLL_SPEED_BASE: 200,
  SCROLL_SPEED_MAX: 500,
  SPEED_RAMP_PER_500PTS: 0.05,
  PLAYER_JUMP_VELOCITY: -450,
  PLAYER_FLY_VELOCITY: -200,
  LASER_CHARGE_MAX: 100,
  LASER_SHOT_COST: 20,
  LASER_SPEED: 700,
  LASER_DRAIN_RATE: 20,      // per second
  LASER_RECHARGE_RATE: 10,   // per second
  GRAVITY: 600,
  GROUND_Y: 630, // Adjusted to visually sit on the foreground road/path
  INVINCIBILITY_DURATION: 2000,  // ms
}
